### PR TITLE
Test for nodejs fixes #21

### LINKED ISSUE #21: superagent-no-cache use error
const nocache = require('superagent-no-cache');
const request = require('superagent');

request
.get('/test')
.use(nocache)
.end(function(err, res){
});

error:
========================================
/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16
el = document.createElement('b'),
^

ReferenceError: document is not defined
at ie (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16:26)
at Object. (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:5:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/Users/akk/sourcecode/test/node_modules/superagent-no-cache/index.js:1:72)

Process finished with exit code 1

### PR DESCRIPTION
**Pull request by piascikj**
This just tests for nodejs before loading the component-ie module, which will throw an error in nodejs.

### CODE REVIEW

**Comment by piascikj** [comment]
@johntron Thanks for providing this package.  What do you think of the change I've proposed?

**Comment by gsf-sellis** [comment]
I think this would be a great PR to merge. Any update?

**Comment by johntron** [comment]
Hey @piascikj and @gsf-sellis - I'm sorry for the late response. Would you mind looking at #23? It may solve your problem, because it completely removes the component-ie dependency.

**Comment by gsf-sellis** [comment]
That is an interesting alternative, but seems to place the onus on the user to add special handling for IE, while this PR keeps IE support under the hood in superagent-no-cache, but just doesn't break in a Node environment. As a user of this module, this PR seems simpler and with fewer side effects (does not change how it is used, would only be a subminor version update, etc.). Thoughts?

**Comment by johntron** [comment]
@gsf-sellis I think it's fine to put the onus on the developer for IE. If you take a look at the pull requests and issues for this project, you'll see people are having lots of problems simply because the component-ie module is included.

I've included the two extra lines required to support IE in the Readme, so it's still pretty obvious how to support IE. Thank you so much for taking the time to submit this PR, but I'm going with my approach.

**Comment by gsf-sellis** [comment]
Ok thanks for a great module we will continue to use and appreciate!

**Pull request closed without merging**
